# Portfonia Makefile
# All developer commands. Run `make help` for the catalog.

SHELL := /bin/bash
.DEFAULT_GOAL := help

# ---- Tool paths ----
PY      := backend/venv/bin/python
PIP     := backend/venv/bin/pip
UVICORN := backend/venv/bin/uvicorn
CELERY  := backend/venv/bin/celery
ALEMBIC := backend/venv/bin/alembic
PYTEST  := backend/venv/bin/pytest
RUFF    := backend/venv/bin/ruff
MYPY    := backend/venv/bin/mypy
COMPOSE := docker compose --env-file .env.local

# ---- Phony ----
.PHONY: help dev infra-up infra-down backend frontend worker scheduler \
        migrate migrate-rollback migrate-status migrate-new db-shell seed \
        test test-backend test-frontend \
        lint lint-fix typecheck \
        logs logs-backend logs-worker shell-cmd

# =====================================================================
# Help
# =====================================================================
help:  ## Show this help
	@printf "Portfonia developer commands\n\n"
	@awk 'BEGIN {FS = ":.*##"} /^[a-zA-Z][a-zA-Z0-9_-]*:.*##/ {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# =====================================================================
# Infrastructure (postgres + redis via Colima)
# =====================================================================
infra-up:  ## Start postgres + redis (auto-starts Colima if needed)
	@colima status >/dev/null 2>&1 || colima start
	@$(COMPOSE) up -d postgres redis
	@echo "[OK] infra ready (postgres:5432, redis:6379)"

infra-down:  ## Stop postgres + redis (data preserved in ./.data)
	@$(COMPOSE) down

# =====================================================================
# Dev orchestration
# =====================================================================
dev: infra-up  ## Start full local stack (infra + backend + worker + scheduler + frontend)
	@echo "[i] launching backend / worker / scheduler / frontend; Ctrl-C to stop all"
	@trap 'kill 0' EXIT; \
	  $(MAKE) -s backend   & \
	  $(MAKE) -s worker    & \
	  $(MAKE) -s scheduler & \
	  $(MAKE) -s frontend  & \
	  wait

backend:  ## Run FastAPI dev server with hot reload
	@cd backend && ../$(UVICORN) app.main:app --reload --host 127.0.0.1 --port 8000

frontend:  ## Run Next.js dev server
	@cd frontend && npm run dev

worker:  ## Run Celery worker
	@cd backend && ../$(CELERY) -A app.tasks worker --loglevel=info

scheduler:  ## Run Celery beat (scheduler)
	@cd backend && ../$(CELERY) -A app.tasks beat --loglevel=info

# =====================================================================
# Database / migrations
# =====================================================================
migrate:  ## Apply all pending Alembic migrations
	@cd backend && ../$(ALEMBIC) upgrade head

migrate-rollback:  ## Roll back the most recent migration
	@cd backend && ../$(ALEMBIC) downgrade -1

migrate-status:  ## Show current migration head
	@cd backend && ../$(ALEMBIC) current

migrate-new:  ## Create new autogenerated migration (usage: make migrate-new MSG="add foo")
	@if [ -z "$(MSG)" ]; then echo "usage: make migrate-new MSG=\"description\""; exit 1; fi
	@cd backend && ../$(ALEMBIC) revision --autogenerate -m "$(MSG)"

db-shell:  ## Open psql shell inside postgres container
	@$(COMPOSE) exec postgres psql -U $${DB_USER:-portfonia} -d $${DB_NAME:-portfonia_dev}

seed:  ## Seed local dev demo data (developer fixture)
	@cd backend && ../$(PY) -m app.scripts.seed

backup:  ## Trigger one pg_dump -> OCI Object Storage backup now (needs BACKUP_OCI_NAMESPACE set)
	@cd backend && ../$(PY) -c "from app.services.db_backup import backup_database; print(backup_database())"

# =====================================================================
# Tests
# =====================================================================
test: test-backend test-frontend  ## Run backend + frontend test suites

test-backend:  ## Run backend pytest
	@cd backend && ../$(PYTEST) -q

test-frontend:  ## Run frontend tests (none yet — typecheck stands in as the gate)
	@cd frontend && if npm run | grep -q '^  test$$'; then npm test --silent; \
		else echo "[i] no frontend test script yet — running typecheck as the gate"; npm run typecheck; fi

# =====================================================================
# Lint / format / typecheck (CLAUDE.md gate order)
# =====================================================================
lint:  ## Lint backend + frontend (non-mutating)
	@cd backend && ../$(RUFF) format --check .
	@cd backend && ../$(RUFF) check .
	@cd frontend && npm run lint

lint-fix:  ## Auto-fix lint and format issues
	@cd backend && ../$(RUFF) format .
	@cd backend && ../$(RUFF) check --fix .
	@cd frontend && npm run lint -- --fix

typecheck:  ## Type check backend (mypy --strict) + frontend (tsc)
	@cd backend && ../$(MYPY) .
	@cd frontend && npm run typecheck

# =====================================================================
# Logs / shell
# =====================================================================
logs:  ## Tail postgres + redis logs
	@$(COMPOSE) logs -f

logs-backend:  ## Tail running backend (only useful if backend was started detached)
	@echo "[i] backend runs in foreground via 'make backend'; use that terminal's output"

logs-worker:  ## Tail running celery worker
	@echo "[i] worker runs in foreground via 'make worker'; use that terminal's output"

shell-cmd:  ## Print command to activate backend venv (use: eval \"$$(make shell-cmd)\")
	@echo "source backend/venv/bin/activate"
