import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect,it,vi } from "vitest";
import { LocaleProvider } from "@/app/_components/locale-provider";
import { ReplaySection } from "./replay-section";
const {getJadeReplay}=vi.hoisted(()=>({getJadeReplay:vi.fn()}));
vi.mock("@/lib/api",async()=>({...await vi.importActual<typeof import("@/lib/api")>("@/lib/api"),getJadeReplay}));
vi.mock("@/lib/auth-actions",()=>({logout:vi.fn()}));
it("A18 callback follows initial and changed successful responses only",async()=>{
  vi.stubGlobal("matchMedia",()=>({matches:false,addEventListener:vi.fn(),removeEventListener:vi.fn()}));
  const result={range:"1Y",status:"pending",base_currency:"USD",benchmark:"sp500",benchmark_symbol:"SPY",points:[],metrics:{portfolio:null,benchmark:null},coverage:{},holdings:[]};
  getJadeReplay.mockResolvedValueOnce(result).mockResolvedValueOnce({...result,range:"3Y",base_currency:"EUR",benchmark:"csi300"}).mockRejectedValueOnce(new Error("offline"));
  const onSettled=vi.fn();
  render(<LocaleProvider routeLocale={null}><ReplaySection onSettled={onSettled}/></LocaleProvider>);
  await waitFor(()=>expect(onSettled).toHaveBeenCalledExactlyOnceWith("USD","sp500"));
  fireEvent.click(screen.getByRole("button",{name:"3Y"}));
  await waitFor(()=>expect(onSettled).toHaveBeenLastCalledWith("EUR","csi300"));
  fireEvent.click(screen.getByRole("button",{name:"5Y"}));
  await screen.findByRole("alert");expect(onSettled).toHaveBeenCalledTimes(2);
  vi.unstubAllGlobals();
});
