"""create holdings table

Revision ID: 01d64b433bd7
Revises: 
Create Date: 2026-05-15 04:56:14.286629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01d64b433bd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('pricing_mode', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('fund_code', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('shares', sa.Numeric(), nullable=True),
    sa.Column('avg_cost', sa.Numeric(), nullable=True),
    sa.Column('current_value', sa.Numeric(), nullable=True),
    sa.Column('asset_type', sa.Text(), nullable=True),
    sa.Column('broker', sa.Text(), nullable=True),
    sa.Column('account', sa.Text(), nullable=True),
    sa.Column('portfolio', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_manual_update', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holdings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    # ### end Alembic commands ###
