"""create reports table

Revision ID: 93ec5cf25995
Revises: 964c96036ca2
Create Date: 2026-05-15 04:57:13.790364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93ec5cf25995'
down_revision: Union[str, Sequence[str], None] = '964c96036ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('disclaimer_version', sa.Text(), nullable=True),
    sa.Column('report_md', sa.Text(), nullable=True),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('report_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('user_id', 'report_date', 'report_type', name='uq_reports_user_date_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
