"""create fx_rates table

Revision ID: 964c96036ca2
Revises: 01d64b433bd7
Create Date: 2026-05-15 04:56:56.045094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '964c96036ca2'
down_revision: Union[str, Sequence[str], None] = '01d64b433bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pair', sa.Text(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'yfinance'"), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_rates')),
    sa.UniqueConstraint('pair', 'rate_date', name='uq_fx_rates_pair_rate_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
